
### **Example 3: GHZ State for 3 Qubits**

$$
\ket{\text{GHZ}_3} = \frac{1}{\sqrt{2}}(\ket{000} + \ket{111})
$$

The state vector is:

$$
\ket{\psi} = \frac{1}{\sqrt{2}} 
\begin{bmatrix}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 1
\end{bmatrix}^T
$$

**Step 1:** Reshape to \((2, 4)\) matrix:

$$
M_1 =
\begin{bmatrix}
\frac{1}{\sqrt{2}} & 0 & 0 & 0 \\
0 & 0 & 0 & \frac{1}{\sqrt{2}}
\end{bmatrix}
$$
"""



In [24]:
using LinearAlgebra

C = [-im/sqrt(8) -im/sqrt(8) im/sqrt(8) im/sqrt(8) im/sqrt(8) im/sqrt(8) -im/sqrt(8) -im/sqrt(8)]
C_reshaped = reshape(C, 2, 4)
println("SVD of C_reshaped:")
M1 = svd(C_reshaped, full=true)


SVD of C_reshaped:


SVD{ComplexF64, Float64, Matrix{ComplexF64}, Vector{Float64}}
U factor:
2×2 Matrix{ComplexF64}:
 -0.707107+1.62099e-65im   0.707107+2.10417e-32im
 -0.707107-1.11022e-16im  -0.707107-1.11022e-16im
singular values:
2-element Vector{Float64}:
 1.0
 3.3993498887762956e-17
Vt factor:
4×4 Matrix{ComplexF64}:
 -2.35514e-17+0.5im       -7.85046e-18-0.5im       …  7.85046e-18+0.5im
     -0.69282-0.519615im      -0.23094-0.173205im         0.23094+0.173205im
          0.0+0.0im           -0.57735+0.0im             0.211325+0.0im
          0.0+0.0im            0.57735+0.0im             0.788675+0.0im

In [26]:
#Building the first site of the MPS

A1_tensor = Array{Float64}(undef, 1, 2, 2) #First site is 1*2*2 tensor with 1 physical inedies with dimension 2 and 2 virtual indices with dimensions 1 and 2
A1_1 = M1.U[:, 1] * M1.S[1] 
A1_tensor = reshape(A1_1, 1 ,2, 1) 
#A1_2 = M1.U[:, 2] * M1.S[2]
#A1_tensor[1, 1, :] = A1_1  # physical index 0
#A1_tensor[1, 2, :] = A1_2  # physical index 1
display(A1_tensor)

1×2×1 Array{ComplexF64, 3}:
[:, :, 1] =
 -0.707107+1.62099e-65im  -0.707107-1.11022e-16im

In [27]:
#Building the second site of the MPS
#Using the V matrix in the SVD of the first site
#Since we have 2 nonzero singular values, we can take the first two columns of V
M1_V = M1.Vt[1:1, :]
M2 = svd(transpose(M1_V), full=true)

SVD{ComplexF64, Float64, Transpose{ComplexF64, Matrix{ComplexF64}}, Vector{Float64}}
U factor:
4×4 transpose(::Matrix{ComplexF64}) with eltype ComplexF64:
 0.0+0.5im   0.4+0.3im   0.4+0.3im  -0.4-0.3im
 0.0-0.5im   0.8+0.1im  -0.2+0.1im   0.2-0.1im
 0.0-0.5im  -0.2+0.1im   0.8+0.1im   0.2-0.1im
 0.0+0.5im   0.2-0.1im   0.2-0.1im   0.8+0.1im
singular values:
1-element Vector{Float64}:
 1.0
Vt factor:
1×1 transpose(::Matrix{ComplexF64}) with eltype ComplexF64:
 1.0 + 0.0im

In [18]:
#Building the second site of the MPS
#The second site is a 2*2*2 tensor with 1 physical indices with dimension 2 and 2 virtual indices with dimensions 2 and 2
#A2_1 = M2.U[:, 1] * M2.S[1]
#A2_2 = M2.U[:, 2] * M2.S[2]
#A2_1_matrix = reshape(A2_1, 2, 2)
#A2_2_matrix = reshape(A2_2, 2, 2)
A2 = M2.U * M2.S[1]
A2_tensor = reshape(A2, 2, 2, 1)

2×2×1 Array{ComplexF64, 3}:
[:, :, 1] =
 -0.707107+0.0im  0.707107+0.0im
  0.707107+0.0im  0.707107+0.0im

In [ ]:
#A2_tensor = Array{Float64}(undef, 2, 2, 2)

#A2_tensor[:, 1, :] = A2_1_matrix  # physical index = 0
#A2_tensor[:, 2, :] = A2_2_matrix  # physical index = 1
#display(A2_tensor)

2×2×2 Array{Float64, 3}:
[:, :, 1] =
 0.707107  0.0
 0.0       0.0

[:, :, 2] =
 0.707107  0.0
 0.0       1.0

In [19]:
#Building the third site of the MPS
#Using the V matrix in the SVD of the second site
M3 = svd(transpose(M2.Vt), full=true)

SVD{ComplexF64, Float64, Matrix{ComplexF64}, Vector{Float64}}
U factor:
1×1 Matrix{ComplexF64}:
 1.0 + 0.0im
singular values:
1-element Vector{Float64}:
 1.0
Vt factor:
1×1 Matrix{ComplexF64}:
 1.0 + 0.0im

In [22]:
A3_tensor = reshape(M3.U, 1, 2 , 1)

DimensionMismatch: DimensionMismatch: new dimensions (1, 2, 1) must be consistent with array size 1

In [ ]:
#A3_tensor = Array{Float64}(undef, 2, 2, 1)

#A3_tensor[:, 1, 1] = M3.U[:, 1]  # physical index = 0
#A3_tensor[:, 2, 1] = M3.U[:, 2]  # physical index = 1

#display(A3_tensor)

2×2×1 Array{Float64, 3}:
[:, :, 1] =
 1.0  0.0
 0.0  1.0

In [8]:
using ITensors

# Define the physical indices for each site (dimension 2)
s1 = Index(2, "s1")
s2 = Index(2, "s2")
s3 = Index(2, "s3")

# Define the bond indices (internal virtual links between tensors)
l1 = Index(2, "l1")
l2 = Index(2, "l2")
# A1: (1, physical, bond) → only indices s1 and l1


A1 = ITensor(s1, l1)
for i in 1:2, j in 1:2
    A1[s1 => i, l1 => j] = A1_tensor[1, i, j]
end

# A2: (bond, physical, bond)
A2 = ITensor(l1, s2, l2)
for i in 1:2, j in 1:2, k in 1:2
    A2[l1 => i, s2 => j, l2 => k] = A2_tensor[i, j, k]
end

# A3: (bond, physical, 1) → just l2 and s3
A3 = ITensor(l2, s3)
for i in 1:2, j in 1:2
    A3[l2 => i, s3 => j] = A3_tensor[i, j, 1]
end

psi = A1 * A2 * A3  

C_reconstructed = reshape(array(psi), 1, 8)

1×8 Matrix{Float64}:
 0.57735  0.0  0.0  0.0  0.57735  0.0  0.0  0.57735